# Generated by Django 5.2.7 on 2025-10-22 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('fecha_fundacion', models.DateField()),
                ('entrenador', models.CharField(max_length=100)),
                ('posicion_entrenador', models.CharField(choices=[('DT', 'Director Técnico'), ('AC', 'Asistente Técnico'), ('PT', 'Preparador Físico'), ('MG', 'Manager General')], default='DT', max_length=2)),
                ('siglas', models.CharField(help_text='Ej: FCB, RMA, ATM', max_length=5)),
                ('color_principal', models.CharField(default='#000000', help_text='Código hexadecimal del color', max_length=7)),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='escudos/')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('posicion', models.CharField(choices=[('POR', 'Portero'), ('DEF', 'Defensa'), ('MED', 'Mediocampista'), ('DEL', 'Delantero')], max_length=3)),
                ('numero_camiseta', models.PositiveIntegerField()),
                ('nacionalidad', models.CharField(max_length=100)),
                ('foto_jugador', models.ImageField(blank=True, null=True, upload_to='jugadores/')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='app_futbol.equipo', verbose_name='Equipo del jugador')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'unique_together': {('equipo', 'numero_camiseta')},
            },
        ),
    ]
